from __future__ import annotations

from typing import Protocol


class FavoriteRepository(Protocol):
    def favorite_keys_for_user(self, user: object) -> list[str]: ...

    def next_sort_order(self, user: object) -> int: ...

    def get_or_create_favorite(self, user: object, menu_key: str, sort_order: int) -> None: ...

    def delete_favorite(self, user: object, menu_key: str) -> None: ...

    def list_favorites(self, user: object) -> dict[str, object]: ...

    def reorder_favorites(self, user: object, menu_keys: list[str]) -> None: ...


class MenuAccessRepository(Protocol):
    def user_group_names(self, user: object) -> set[str]: ...

    def accessible_menu_group_keys(self, user: object) -> set[str]: ...
