# Generated by Django 6.0.5 on 2026-06-15 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_receipt_data_forward(apps, schema_editor):
    OldSupplier = apps.get_model("receipt_comparison", "ReceiptSupplier")
    OldReceiving = apps.get_model("receipt_comparison", "ReceiptReceivingSetting")
    OldSubcontractor = apps.get_model("receipt_comparison", "ReceiptSubcontractor")
    OldFileImport = apps.get_model("receipt_comparison", "ReceiptFileImport")
    OldResult = apps.get_model("receipt_comparison", "ReceiptComparisonResult")

    FPSupplier = apps.get_model("receipt_comparison", "FinishedProductReceiptSupplier")
    SPSupplier = apps.get_model("receipt_comparison", "SuppliedPartsReceiptSupplier")
    FPReceiving = apps.get_model("receipt_comparison", "FinishedProductReceivingSetting")
    SPReceiving = apps.get_model("receipt_comparison", "SuppliedPartsReceivingSetting")
    SPSubcontractor = apps.get_model("receipt_comparison", "SuppliedPartsSubcontractor")
    FPFileImport = apps.get_model("receipt_comparison", "FinishedProductFileImport")
    SPFileImport = apps.get_model("receipt_comparison", "SuppliedPartsFileImport")
    FPResult = apps.get_model("receipt_comparison", "FinishedProductComparisonResult")
    SPResult = apps.get_model("receipt_comparison", "SuppliedPartsComparisonResult")

    fp_supplier_map: dict[int, object] = {}
    sp_supplier_map: dict[int, object] = {}

    for old in OldSupplier.objects.all().order_by("id"):
        if old.comparison_type == "finished_product":
            customer_code = (old.customer_code or "").strip()
            if not customer_code:
                continue
            new_supplier, _ = FPSupplier.objects.update_or_create(
                customer_code=customer_code,
                defaults={
                    "name": old.name,
                    "direct_delivery_customer_code": old.direct_delivery_customer_code,
                    "exclusion": old.exclusion,
                    "created_at": old.created_at,
                    "updated_at": old.updated_at,
                },
            )
            fp_supplier_map[old.id] = new_supplier
            continue
        if old.comparison_type == "supplied_parts":
            vendor_code = (old.vendor_code or old.customer_code or "").strip()
            if not vendor_code:
                continue
            new_supplier, _ = SPSupplier.objects.update_or_create(
                vendor_code=vendor_code,
                defaults={
                    "name": old.name,
                    "exclusion": old.exclusion,
                    "created_at": old.created_at,
                    "updated_at": old.updated_at,
                },
            )
            sp_supplier_map[old.id] = new_supplier

    for old in OldReceiving.objects.all().order_by("id"):
        old_supplier_id = old.supplier_id
        if old_supplier_id in fp_supplier_map:
            FPReceiving.objects.update_or_create(
                supplier=fp_supplier_map[old_supplier_id],
                delivery_place=old.delivery_place,
                defaults={
                    "enabled": old.enabled,
                    "created_by_id": old.created_by_id,
                    "updated_by_id": old.updated_by_id,
                    "created_at": old.created_at,
                    "updated_at": old.updated_at,
                },
            )
        elif old_supplier_id in sp_supplier_map:
            SPReceiving.objects.update_or_create(
                supplier=sp_supplier_map[old_supplier_id],
                delivery_place=old.delivery_place,
                defaults={
                    "enabled": old.enabled,
                    "created_by_id": old.created_by_id,
                    "updated_by_id": old.updated_by_id,
                    "created_at": old.created_at,
                    "updated_at": old.updated_at,
                },
            )

    for old in OldSubcontractor.objects.all().order_by("id"):
        supplier = sp_supplier_map.get(old.supplier_id)
        vendor_code = (old.vendor_code or old.customer_code or "").strip()
        if supplier and vendor_code:
            SPSubcontractor.objects.update_or_create(
                supplier=supplier,
                vendor_code=vendor_code,
            )

    fp_file_map: dict[int, object] = {}
    sp_file_map: dict[int, object] = {}
    for old in OldFileImport.objects.all().order_by("id"):
        if old.comparison_type == "finished_product":
            supplier = fp_supplier_map.get(old.supplier_id)
            if not supplier:
                continue
            new_file = FPFileImport.objects.create(
                supplier=supplier,
                original_file_name=old.original_file_name,
                stored_file_name=old.stored_file_name,
                receipt_date=old.receipt_date,
                imported_by_id=old.imported_by_id,
                imported_at=old.imported_at,
            )
            fp_file_map[old.id] = new_file
            continue
        if old.comparison_type == "supplied_parts":
            supplier = sp_supplier_map.get(old.supplier_id)
            if not supplier:
                continue
            new_file = SPFileImport.objects.create(
                supplier=supplier,
                original_file_name=old.original_file_name,
                stored_file_name=old.stored_file_name,
                receipt_date=old.receipt_date,
                imported_by_id=old.imported_by_id,
                imported_at=old.imported_at,
            )
            sp_file_map[old.id] = new_file

    for old in OldResult.objects.all().order_by("id"):
        common = {
            "receipt_flag": old.receipt_flag,
            "mari_item_cd": old.mari_item_cd,
            "mari_date": old.mari_date,
            "mari_qty": old.mari_qty,
            "delivery_place": old.delivery_place,
            "supplier_item_cd": old.supplier_item_cd,
            "supplier_delivery_month_day": old.supplier_delivery_month_day,
            "supplier_qty": old.supplier_qty,
            "supplier_cancel_qty": old.supplier_cancel_qty,
            "supplier_name": old.supplier_name,
            "remarks": old.remarks,
            "created_at": old.created_at,
            "updated_by_id": old.updated_by_id,
            "updated_at": old.updated_at,
        }
        if old.comparison_type == "finished_product":
            supplier = fp_supplier_map.get(old.supplier_id)
            if not supplier:
                continue
            FPResult.objects.create(
                supplier=supplier,
                file_import=fp_file_map.get(old.file_import_id),
                **common,
            )
            continue
        if old.comparison_type == "supplied_parts":
            supplier = sp_supplier_map.get(old.supplier_id)
            if not supplier:
                continue
            SPResult.objects.create(
                supplier=supplier,
                file_import=sp_file_map.get(old.file_import_id),
                **common,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_comparison', '0002_receipt_supplier_vendor_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_flag', models.PositiveSmallIntegerField(choices=[(0, '×'), (1, '〇'), (2, '△')], default=0)),
                ('mari_item_cd', models.CharField(blank=True, max_length=120)),
                ('mari_date', models.CharField(blank=True, max_length=20)),
                ('mari_qty', models.CharField(blank=True, max_length=40)),
                ('delivery_place', models.CharField(blank=True, max_length=80)),
                ('supplier_item_cd', models.CharField(blank=True, max_length=120)),
                ('supplier_delivery_month_day', models.CharField(blank=True, max_length=4)),
                ('supplier_qty', models.CharField(blank=True, max_length=40)),
                ('supplier_cancel_qty', models.CharField(blank=True, max_length=40)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['receipt_flag', 'mari_item_cd', 'supplier_item_cd', 'mari_date', 'supplier_delivery_month_day'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductFileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('receipt_date', models.DateField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-receipt_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductReceiptSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('customer_code', models.CharField(max_length=40)),
                ('direct_delivery_customer_code', models.CharField(blank=True, max_length=40)),
                ('exclusion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductReceivingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_place', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['delivery_place'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedPartsComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_flag', models.PositiveSmallIntegerField(choices=[(0, '×'), (1, '〇'), (2, '△')], default=0)),
                ('mari_item_cd', models.CharField(blank=True, max_length=120)),
                ('mari_date', models.CharField(blank=True, max_length=20)),
                ('mari_qty', models.CharField(blank=True, max_length=40)),
                ('delivery_place', models.CharField(blank=True, max_length=80)),
                ('supplier_item_cd', models.CharField(blank=True, max_length=120)),
                ('supplier_delivery_month_day', models.CharField(blank=True, max_length=4)),
                ('supplier_qty', models.CharField(blank=True, max_length=40)),
                ('supplier_cancel_qty', models.CharField(blank=True, max_length=40)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['receipt_flag', 'mari_item_cd', 'supplier_item_cd', 'mari_date', 'supplier_delivery_month_day'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedPartsFileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('receipt_date', models.DateField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-receipt_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedPartsReceiptSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vendor_code', models.CharField(max_length=40)),
                ('exclusion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedPartsReceivingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_place', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['delivery_place'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedPartsSubcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['vendor_code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='receiptcomparisonresult',
            name='receipt_result_flag_idx',
        ),
        migrations.RemoveIndex(
            model_name='receiptcomparisonresult',
            name='receipt_result_item_idx',
        ),
        migrations.RemoveIndex(
            model_name='receiptfileimport',
            name='receipt_file_lookup_idx',
        ),
        migrations.RemoveConstraint(
            model_name='receiptreceivingsetting',
            name='unique_receipt_receiving_place',
        ),
        migrations.RemoveConstraint(
            model_name='receiptsubcontractor',
            name='unique_receipt_subcontractor',
        ),
        migrations.RemoveConstraint(
            model_name='receiptsupplier',
            name='unique_receipt_supplier_code',
        ),
        migrations.AddField(
            model_name='finishedproductcomparisonresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fp_receipt_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedproductfileimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_receipt_file_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedproductcomparisonresult',
            name='file_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='receipt_comparison.finishedproductfileimport'),
        ),
        migrations.AddConstraint(
            model_name='finishedproductreceiptsupplier',
            constraint=models.UniqueConstraint(fields=('customer_code',), name='unique_fp_receipt_supplier_customer_code'),
        ),
        migrations.AddField(
            model_name='finishedproductfileimport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_file_imports', to='receipt_comparison.finishedproductreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='finishedproductcomparisonresult',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_results', to='receipt_comparison.finishedproductreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='finishedproductreceivingsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fp_receipt_receiving_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedproductreceivingsetting',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_settings', to='receipt_comparison.finishedproductreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='finishedproductreceivingsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fp_receipt_receiving_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliedpartscomparisonresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sp_receipt_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliedpartsfileimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_receipt_file_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliedpartscomparisonresult',
            name='file_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='receipt_comparison.suppliedpartsfileimport'),
        ),
        migrations.AddConstraint(
            model_name='suppliedpartsreceiptsupplier',
            constraint=models.UniqueConstraint(fields=('vendor_code',), name='unique_sp_receipt_supplier_vendor_code'),
        ),
        migrations.AddField(
            model_name='suppliedpartsfileimport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_file_imports', to='receipt_comparison.suppliedpartsreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='suppliedpartscomparisonresult',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_results', to='receipt_comparison.suppliedpartsreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='suppliedpartsreceivingsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sp_receipt_receiving_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliedpartsreceivingsetting',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_settings', to='receipt_comparison.suppliedpartsreceiptsupplier'),
        ),
        migrations.AddField(
            model_name='suppliedpartsreceivingsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sp_receipt_receiving_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliedpartssubcontractor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='receipt_comparison.suppliedpartsreceiptsupplier'),
        ),
        migrations.RunPython(migrate_receipt_data_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='receiptcomparisonresult',
            name='file_import',
        ),
        migrations.RemoveField(
            model_name='receiptcomparisonresult',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptcomparisonresult',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='receiptfileimport',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='receiptfileimport',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptreceivingsetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiptreceivingsetting',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptreceivingsetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='receiptsubcontractor',
            name='supplier',
        ),
        migrations.AddIndex(
            model_name='finishedproductfileimport',
            index=models.Index(fields=['supplier', 'receipt_date'], name='fp_receipt_file_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproductcomparisonresult',
            index=models.Index(fields=['supplier', 'receipt_flag'], name='fp_receipt_result_flag_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproductcomparisonresult',
            index=models.Index(fields=['supplier', 'mari_item_cd'], name='fp_receipt_result_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='finishedproductreceivingsetting',
            constraint=models.UniqueConstraint(fields=('supplier', 'delivery_place'), name='unique_fp_receipt_receiving_place'),
        ),
        migrations.AddIndex(
            model_name='suppliedpartsfileimport',
            index=models.Index(fields=['supplier', 'receipt_date'], name='sp_receipt_file_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliedpartscomparisonresult',
            index=models.Index(fields=['supplier', 'receipt_flag'], name='sp_receipt_result_flag_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliedpartscomparisonresult',
            index=models.Index(fields=['supplier', 'mari_item_cd'], name='sp_receipt_result_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliedpartsreceivingsetting',
            constraint=models.UniqueConstraint(fields=('supplier', 'delivery_place'), name='unique_sp_receipt_receiving_place'),
        ),
        migrations.AddConstraint(
            model_name='suppliedpartssubcontractor',
            constraint=models.UniqueConstraint(fields=('supplier', 'vendor_code'), name='unique_sp_receipt_subcontractor'),
        ),
        migrations.DeleteModel(
            name='ReceiptComparisonResult',
        ),
        migrations.DeleteModel(
            name='ReceiptFileImport',
        ),
        migrations.DeleteModel(
            name='ReceiptReceivingSetting',
        ),
        migrations.DeleteModel(
            name='ReceiptSubcontractor',
        ),
        migrations.DeleteModel(
            name='ReceiptSupplier',
        ),
    ]
