# Generated by Django 5.2 on 2026-08-27 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_normalize_menu_group_access_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=80)),
                ('usage_type', models.CharField(choices=[('VIEW', '表示'), ('EXPORT', '出力')], max_length=10)),
                ('used_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_menu_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['used_at'], name='menu_usage_used_at_idx'), models.Index(fields=['menu_key', '-used_at'], name='menu_usage_menu_key_idx'), models.Index(fields=['user', '-used_at'], name='menu_usage_user_idx'), models.Index(fields=['usage_type', '-used_at'], name='menu_usage_type_idx')],
            },
        ),
    ]
