# Generated by Django 5.2 on 2026-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_order_alert', '0011_rename_confirmed_alert_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorderalertsettings',
            name='default_lead_time_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='inventoryorderalertsettings',
            name='safety_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='inventoryorderalertsettings',
            name='watch_months',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
